SET NOCOUNT ON;

SELECT 'DATABASE' AS Metric, DB_NAME() AS ValueText, NULL AS ValueNumber
UNION ALL SELECT 'USERS_TOTAL', NULL, COUNT(*) FROM AspNetUsers
UNION ALL SELECT 'DEPOTS', NULL, COUNT(*) FROM F_DEPOT
UNION ALL SELECT 'ZONES', NULL, COUNT(*) FROM F_DEPOT_ZONE
UNION ALL SELECT 'CATALOGUES', NULL, COUNT(*) FROM F_CATALOGUE
UNION ALL SELECT 'ARTICLES', NULL, COUNT(*) FROM F_ARTICLE
UNION ALL SELECT 'STOCKS', NULL, COUNT(*) FROM F_ARTSTOCK
UNION ALL SELECT 'DEVIS', NULL, COUNT(*) FROM F_DEVIS_ENTETE
UNION ALL SELECT 'DEVIS_LIGNES', NULL, COUNT(*) FROM F_DEVIS_LIGNE
UNION ALL SELECT 'COMMANDES', NULL, COUNT(*) FROM F_DOCENTETE
UNION ALL SELECT 'LIGNES_COMMANDES', NULL, COUNT(*) FROM F_DOCLIGNE
UNION ALL SELECT 'LIVRAISONS', NULL, COUNT(*) FROM F_LIVRAISON
UNION ALL SELECT 'TRANSFERTS', NULL, COUNT(*) FROM F_TRANSFERT
UNION ALL SELECT 'RECLAMATIONS', NULL, COUNT(*) FROM F_RECLAMATION
UNION ALL SELECT 'PAIEMENTS', NULL, COUNT(*) FROM B_PAIEMENT;

SELECT r.Name AS RoleName, COUNT(ur.UserId) AS UsersCount
FROM AspNetRoles r
LEFT JOIN AspNetUserRoles ur ON ur.RoleId = r.Id
GROUP BY r.Name
ORDER BY r.Name;

SELECT CL_Niveau, COUNT(*) AS CataloguesCount
FROM F_CATALOGUE
GROUP BY CL_Niveau
ORDER BY CL_Niveau;

SELECT 'ARTICLES_WITHOUT_CATEGORY' AS CheckName, COUNT(*) AS Issues
FROM F_ARTICLE a
WHERE NOT EXISTS (SELECT 1 FROM F_CATALOGUE c WHERE c.CL_No = a.CL_No3)
UNION ALL
SELECT 'DUPLICATE_ARTICLE_DESIGNATIONS', COUNT(*)
FROM (
    SELECT AR_Design
    FROM F_ARTICLE
    GROUP BY AR_Design
    HAVING COUNT(*) > 1
) d
UNION ALL
SELECT 'STOCK_WITHOUT_ARTICLE', COUNT(*)
FROM F_ARTSTOCK s
WHERE NOT EXISTS (SELECT 1 FROM F_ARTICLE a WHERE a.AR_Ref = s.AR_Ref)
UNION ALL
SELECT 'STOCK_WITHOUT_DEPOT', COUNT(*)
FROM F_ARTSTOCK s
WHERE NOT EXISTS (SELECT 1 FROM F_DEPOT d WHERE d.DE_No = s.DE_No)
UNION ALL
SELECT 'COMMANDES_WITHOUT_CLIENT', COUNT(*)
FROM F_DOCENTETE o
WHERE o.DO_ClientUserId IS NULL OR NOT EXISTS (SELECT 1 FROM AspNetUsers u WHERE u.Id = o.DO_ClientUserId)
UNION ALL
SELECT 'LIGNES_WITHOUT_ORDER', COUNT(*)
FROM F_DOCLIGNE l
WHERE NOT EXISTS (SELECT 1 FROM F_DOCENTETE o WHERE o.DO_Piece = l.DO_Piece)
UNION ALL
SELECT 'LIGNES_WITHOUT_ARTICLE', COUNT(*)
FROM F_DOCLIGNE l
WHERE NOT EXISTS (SELECT 1 FROM F_ARTICLE a WHERE a.AR_Ref = l.AR_Ref)
UNION ALL
SELECT 'LIVRAISONS_WITHOUT_ORDER', COUNT(*)
FROM F_LIVRAISON li
WHERE NOT EXISTS (SELECT 1 FROM F_DOCENTETE o WHERE o.DO_Piece = li.DO_Piece)
UNION ALL
SELECT 'TRANSFERTS_WITHOUT_SOURCE_DEPOT', COUNT(*)
FROM F_TRANSFERT t
WHERE NOT EXISTS (SELECT 1 FROM F_DEPOT d WHERE d.DE_No = t.SourceDepotNo)
UNION ALL
SELECT 'TRANSFERTS_WITHOUT_DESTINATION_DEPOT', COUNT(*)
FROM F_TRANSFERT t
WHERE NOT EXISTS (SELECT 1 FROM F_DEPOT d WHERE d.DE_No = t.DestinationDepotNo)
UNION ALL
SELECT 'TRANSFERTS_WITHOUT_ARTICLE', COUNT(*)
FROM F_TRANSFERT t
WHERE NOT EXISTS (SELECT 1 FROM F_ARTICLE a WHERE a.AR_Ref = t.ArRef);
