// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.data;

#nullable disable

namespace Web_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511234458_ConfirmatriceSession")]
    partial class ConfirmatriceSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.B_PAIEMENT", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("PA_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PA_Fournisseur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PA_IsSandbox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("PA_Mode")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PA_Montant")
                        .HasColumnType("decimal(24,13)");

                    b.Property<string>("PA_ProviderPaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PA_Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("PA_Statut")
                        .HasColumnType("smallint");

                    b.Property<string>("PA_StatutExterne")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PA_Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.HasIndex("PA_ProviderPaymentId")
                        .HasFilter("[PA_ProviderPaymentId] IS NOT NULL");

                    b.HasIndex("PA_Reference")
                        .IsUnique()
                        .HasFilter("[PA_Reference] IS NOT NULL");

                    b.HasIndex("PA_Statut");

                    b.HasIndex("DO_Piece", "cbMarq");

                    b.ToTable("B_PAIEMENT");
                });

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.F_LIVRAISON", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("DepotPassageNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Encaisse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EncaisseAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LI_Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LI_CodePostal")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("LI_Commentaire")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("LI_DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LI_DateLivree")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LI_DateReplanification")
                        .HasColumnType("datetime2");

                    b.Property<string>("LI_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LI_Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LI_PieceSage")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("LI_Statut")
                        .HasColumnType("smallint");

                    b.Property<string>("LI_Ville")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontantEncaisse")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("RemisAuDepot")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemisAuDepotAt")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.HasIndex("LI_Statut", "DepotPassageNumber")
                        .HasDatabaseName("IX_F_LIVRAISON_DepotPassage");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LI_Statut", "DepotPassageNumber"), new[] { "DO_Piece", "LivreurId" });

                    b.HasIndex("LivreurId", "EncaisseAt", "RemisAuDepot");

                    b.ToTable("F_LIVRAISON");
                });

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.F_TAXE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<int>("TX_CODE")
                        .HasColumnType("int");

                    b.Property<string>("TX_Compte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_LIBELLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TX_TAUX")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short>("TX_Type")
                        .HasColumnType("smallint");

                    b.HasKey("cbMarq");

                    b.ToTable("F_TAXE");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web_Api.Auth.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerProfilecbMarq")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfilecbMarq");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Web_Api.Auth.Entities.ProfilUtilisateur", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AdresseComplementaire")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeClientSage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeDepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEmploye")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereSynchronisation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delegation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("EstSynchroniseAvecSage")
                        .HasColumnType("bit");

                    b.Property<int>("Gouvernorat")
                        .HasColumnType("int");

                    b.Property<bool>("IsInPause")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAssignmentAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("MatriculeFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomComplet")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomSociete")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroTVA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PlafondCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Remise")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TypeClient")
                        .HasColumnType("int");

                    b.Property<int?>("TypeProfil")
                        .HasColumnType("int");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZoneLivraison")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("cbMarq");

                    b.ToTable("ProfilsUtilisateurs");
                });

            modelBuilder.Entity("Web_Api.Model.CMS_HOMEPAGE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublishedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique();

                    b.ToTable("CMS_HOMEPAGE");
                });

            modelBuilder.Entity("Web_Api.Model.CommandeConfirmationLock", b =>
                {
                    b.Property<string>("DoPiece")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LockedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoPiece");

                    b.ToTable("CommandeConfirmationLocks");
                });

            modelBuilder.Entity("Web_Api.Model.F_APP_CONFIG", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("F_APP_CONFIG", t =>
                        {
                            t.HasCheckConstraint("CK_AppConfig_OneRow", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("Web_Api.Model.F_ARTICLE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_CodeBarre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Design")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AR_PrixTTC")
                        .HasColumnType("smallint");

                    b.Property<decimal>("AR_PrixVen")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short>("AR_Publie")
                        .HasColumnType("smallint");

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AR_Sommeil")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_SuiviStock")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_Type")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_UniteVen")
                        .HasColumnType("smallint");

                    b.Property<int>("CL_No1")
                        .HasColumnType("int");

                    b.Property<int>("CL_No2")
                        .HasColumnType("int");

                    b.Property<int>("CL_No3")
                        .HasColumnType("int");

                    b.Property<int>("CL_No4")
                        .HasColumnType("int");

                    b.Property<string>("FA_CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cbMarq");

                    b.ToTable("F_ARTICLE");
                });

            modelBuilder.Entity("Web_Api.Model.F_ARTICLE_IMAGE", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CloudinaryPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("F_ARTICLE_IMAGE");
                });

            modelBuilder.Entity("Web_Api.Model.F_ARTSTOCK", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AS_Principal")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("AS_QteMaxi")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("AS_QteMini")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("AS_QteRes")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("AS_QteSto")
                        .HasColumnType("decimal(24,13)");

                    b.Property<int>("DE_No")
                        .HasColumnType("int");

                    b.HasKey("cbMarq");

                    b.ToTable("F_ARTSTOCK");
                });

            modelBuilder.Entity("Web_Api.Model.F_AVIS_COMMANDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandePiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("CommandePiece")
                        .IsUnique();

                    b.ToTable("F_AVIS_COMMANDE");
                });

            modelBuilder.Entity("Web_Api.Model.F_AVIS_PROMPT_STATE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandePiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPromptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromptCount")
                        .HasColumnType("int");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("CommandePiece")
                        .IsUnique();

                    b.ToTable("F_AVIS_PROMPT_STATE");
                });

            modelBuilder.Entity("Web_Api.Model.F_CATALOGUE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("CL_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CL_Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CL_Niveau")
                        .HasColumnType("smallint");

                    b.Property<int>("CL_No")
                        .HasColumnType("int");

                    b.Property<int>("CL_NoParent")
                        .HasColumnType("int");

                    b.Property<short>("CL_Stock")
                        .HasColumnType("smallint");

                    b.HasKey("cbMarq");

                    b.ToTable("F_CATALOGUE");
                });

            modelBuilder.Entity("Web_Api.Model.F_CHATBOT_ACTION_LOG", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExecutedAt");

                    b.ToTable("F_CHATBOT_ACTION_LOG");
                });

            modelBuilder.Entity("Web_Api.Model.F_CHATBOT_INSIGHT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminFeedback")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ShownToAdminAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DismissedAt");

                    b.ToTable("F_CHATBOT_INSIGHT");
                });

            modelBuilder.Entity("Web_Api.Model.F_CHATBOT_MESSAGE", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("F_CHATBOT_MESSAGE");
                });

            modelBuilder.Entity("Web_Api.Model.F_CHATBOT_PENDING_ACTION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("F_CHATBOT_PENDING_ACTION");
                });

            modelBuilder.Entity("Web_Api.Model.F_CHATBOT_SESSION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastActivityAt");

                    b.ToTable("F_CHATBOT_SESSION");
                });

            modelBuilder.Entity("Web_Api.Model.F_CLIENT_ADDRESS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delegation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gouvernorat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.ToTable("F_CLIENT_ADDRESS");
                });

            modelBuilder.Entity("Web_Api.Model.F_CLIENT_DEVICE_TOKEN", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("F_CLIENT_DEVICE_TOKEN");
                });

            modelBuilder.Entity("Web_Api.Model.F_CONFIRMATRICE_SESSION", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConfirmatriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndReason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt")
                        .HasDatabaseName("IX_ConfirmatriceSession_EndedAt");

                    b.HasIndex("ConfirmatriceId", "StartedAt")
                        .HasDatabaseName("IX_ConfirmatriceSession_User_Start");

                    b.ToTable("F_CONFIRMATRICE_SESSION");
                });

            modelBuilder.Entity("Web_Api.Model.F_DEPOT", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DE_Adresse")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("DE_Banque")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DE_Code")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DE_CodePostal")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DE_CodeSociete")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DE_Complement")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("DE_Intitule")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("DE_No")
                        .HasColumnType("int");

                    b.Property<string>("DE_Pays")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<short?>("DE_Principal")
                        .HasColumnType("smallint");

                    b.Property<string>("DE_Ville")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("cbMarq");

                    b.ToTable("F_DEPOT");
                });

            modelBuilder.Entity("Web_Api.Model.F_DOCENTETE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<Guid?>("AssignedLivreurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CT_NumPayeur")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("CommandeOriginalePiece")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("DE_No")
                        .HasColumnType("int");

                    b.Property<string>("DO_AdresseLivraison")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DO_ClientMode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid?>("DO_ClientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DO_CodePostalLivraison")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime?>("DO_Date")
                        .HasColumnType("datetime2");

                    b.Property<short?>("DO_Domaine")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("DO_FraisLivraison")
                        .HasColumnType("decimal(24,13)");

                    b.Property<string>("DO_InstructionsLivraison")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DO_LatitudeLivraison")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_LongitudeLivraison")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_ModeLivraison")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DO_ModePaiement")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DO_NetAPayer")
                        .HasColumnType("decimal(24,13)");

                    b.Property<string>("DO_PassagerAdresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DO_PassagerAdresseComplementaire")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DO_PassagerCIN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_PassagerCodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_PassagerDelegation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DO_PassagerGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DO_PassagerMatriculeFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DO_PassagerNomComplet")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DO_PassagerNomSociete")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DO_PassagerNumeroTVA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DO_PassagerRegistreCommerce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DO_PassagerTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DO_PassagerTypeClient")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DO_Piece")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("DO_Ref")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_RepereLivraison")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DO_TelephoneLivraison")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_Tiers")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal?>("DO_TimbreFiscal")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DO_TotalHT")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DO_TotalHTNet")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DO_TotalTTC")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short?>("DO_Type")
                        .HasColumnType("smallint");

                    b.Property<short?>("DO_Valide")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("DO_VendeurUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DO_VilleLivraison")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("EchangeArticleLivraison")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EchangeArticleRetour")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActiveDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("ProximityAlertSent")
                        .HasColumnType("bit");

                    b.Property<int?>("ReclamationOrigineId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCommande")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.HasIndex("AssignedLivreurId");

                    b.HasIndex("IsActiveDelivery", "AssignedLivreurId")
                        .HasDatabaseName("IX_F_DOCENTETE_ActiveDelivery");

                    b.ToTable("F_DOCENTETE");
                });

            modelBuilder.Entity("Web_Api.Model.F_DOCLIGNE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_Ref")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("CT_Num")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("DL_Design")
                        .HasMaxLength(69)
                        .HasColumnType("nvarchar(69)");

                    b.Property<decimal?>("DL_MontantHT")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DL_MontantTTC")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DL_PrixUnitaire")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("DL_Qte")
                        .HasColumnType("decimal(24,13)");

                    b.Property<DateTime?>("DO_Date")
                        .HasColumnType("datetime2");

                    b.Property<short?>("DO_Domaine")
                        .HasColumnType("smallint");

                    b.Property<string>("DO_Piece")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short?>("DO_Type")
                        .HasColumnType("smallint");

                    b.Property<string>("LigneType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.HasIndex("LigneType");

                    b.ToTable("F_DOCLIGNE");
                });

            modelBuilder.Entity("Web_Api.Model.F_LIVRAISON_HISTORIQUE", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepotPassageNumber")
                        .HasColumnType("int");

                    b.Property<string>("DoPiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("LivreurProfileId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LivreurUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Motif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DoPiece", "CreatedAt");

                    b.HasIndex("LivreurUserId", "CreatedAt");

                    b.ToTable("F_LIVRAISON_HISTORIQUE");
                });

            modelBuilder.Entity("Web_Api.Model.F_LIVREUR_ABANDON_LOG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandePiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LivreurUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LivreurUserId", "CreatedAt");

                    b.ToTable("F_LIVREUR_ABANDON_LOG");
                });

            modelBuilder.Entity("Web_Api.Model.F_LIVREUR_ACTION_LOG", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HttpResponse")
                        .HasColumnType("int");

                    b.Property<Guid>("LivreurUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientActionId")
                        .IsUnique();

                    b.HasIndex("LivreurUserId", "ProcessedAt");

                    b.ToTable("F_LIVREUR_ACTION_LOG");
                });

            modelBuilder.Entity("Web_Api.Model.F_LIVREUR_POSITION", b =>
                {
                    b.Property<Guid>("LivreurUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Accuracy")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsBroadcasting")
                        .HasColumnType("bit");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LivreurUserId");

                    b.ToTable("F_LIVREUR_POSITION");
                });

            modelBuilder.Entity("Web_Api.Model.F_LIVREUR_POSITION_HISTORY", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Accuracy")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClientActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<Guid>("LivreurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientActionId")
                        .IsUnique()
                        .HasFilter("[ClientActionId] IS NOT NULL");

                    b.HasIndex("LivreurId", "CapturedAt")
                        .HasDatabaseName("IX_LivreurPosHistory");

                    b.ToTable("F_LIVREUR_POSITION_HISTORY");
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArRef")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodeReclamation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("CorrectionAppliquee")
                        .HasColumnType("bit");

                    b.Property<string>("CorrectionProposee")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DoPiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("EchangeDemandeText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FirstAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastClientReplyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoteInterne")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priorite")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReprogrammationCreneau")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReprogrammationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TentativesCount")
                        .HasColumnType("int");

                    b.Property<string>("TypeCas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypeReclamation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VisibleClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("CodeReclamation")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DoPiece");

                    b.HasIndex("Source");

                    b.HasIndex("Statut");

                    b.HasIndex("TypeCas");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VisibleClient");

                    b.ToTable("F_RECLAMATION");
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION_PHOTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReclamationId");

                    b.ToTable("F_RECLAMATION_PHOTO");
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION_TENTATIVE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandePiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateJour")
                        .HasColumnType("date");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("LivreurUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommandePiece");

                    b.HasIndex("ReclamationId");

                    b.HasIndex("CommandePiece", "DateJour")
                        .IsUnique();

                    b.ToTable("F_RECLAMATION_TENTATIVE");
                });

            modelBuilder.Entity("Web_Api.Model.F_SMS_LOG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoPiece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DoPiece", "SentAt");

                    b.ToTable("F_SMS_LOG");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Web_Api.Auth.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Web_Api.Auth.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api.Auth.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Web_Api.Auth.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_Api.Auth.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Web_Api.Auth.Entities.ProfilUtilisateur", "CustomerProfile")
                        .WithMany()
                        .HasForeignKey("CustomerProfilecbMarq");

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION_PHOTO", b =>
                {
                    b.HasOne("Web_Api.Model.F_RECLAMATION", null)
                        .WithMany("Photos")
                        .HasForeignKey("ReclamationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION_TENTATIVE", b =>
                {
                    b.HasOne("Web_Api.Model.F_RECLAMATION", null)
                        .WithMany("Tentatives")
                        .HasForeignKey("ReclamationId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Web_Api.Model.F_RECLAMATION", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Tentatives");
                });
#pragma warning restore 612, 618
        }
    }
}
