// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.data;

#nullable disable

namespace Web_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212084538_melek1")]
    partial class melek1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.B_PAIEMENT", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("PA_Date")
                        .HasColumnType("datetime2");

                    b.Property<short>("PA_Mode")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PA_Montant")
                        .HasColumnType("decimal(24,13)");

                    b.Property<string>("PA_Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("PA_Statut")
                        .HasColumnType("smallint");

                    b.Property<string>("PA_Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.ToTable("B_PAIEMENT");
                });

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.F_LIVRAISON", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LI_Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LI_CodePostal")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("LI_DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LI_DateLivree")
                        .HasColumnType("datetime2");

                    b.Property<string>("LI_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LI_Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LI_PieceSage")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("LI_Statut")
                        .HasColumnType("smallint");

                    b.Property<string>("LI_Ville")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("int");

                    b.HasKey("cbMarq");

                    b.ToTable("F_LIVRAISON");
                });

            modelBuilder.Entity("MODELS_CREATEUR.MODELS_SAGE.F_TAXE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<int>("TX_CODE")
                        .HasColumnType("int");

                    b.Property<string>("TX_Compte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_LIBELLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TX_TAUX")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short>("TX_Type")
                        .HasColumnType("smallint");

                    b.HasKey("cbMarq");

                    b.ToTable("F_TAXE");
                });

            modelBuilder.Entity("Web_Api.Model.F_ARTICLE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_CodeBarre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AR_Design")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AR_PrixTTC")
                        .HasColumnType("smallint");

                    b.Property<decimal>("AR_PrixVen")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short>("AR_Publie")
                        .HasColumnType("smallint");

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AR_Sommeil")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_SuiviStock")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_Type")
                        .HasColumnType("smallint");

                    b.Property<short>("AR_UniteVen")
                        .HasColumnType("smallint");

                    b.Property<int>("CL_No1")
                        .HasColumnType("int");

                    b.Property<int>("CL_No2")
                        .HasColumnType("int");

                    b.Property<int>("CL_No3")
                        .HasColumnType("int");

                    b.Property<int>("CL_No4")
                        .HasColumnType("int");

                    b.Property<string>("FA_CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cbMarq");

                    b.ToTable("F_ARTICLE");
                });

            modelBuilder.Entity("Web_Api.Model.F_ARTSTOCK", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AS_Principal")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("AS_QteMaxi")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal?>("AS_QteMini")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("AS_QteRes")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("AS_QteSto")
                        .HasColumnType("decimal(24,13)");

                    b.Property<int>("DE_No")
                        .HasColumnType("int");

                    b.HasKey("cbMarq");

                    b.ToTable("F_ARTSTOCK");
                });

            modelBuilder.Entity("Web_Api.Model.F_CATALOGUE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("CL_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CL_Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CL_Niveau")
                        .HasColumnType("smallint");

                    b.Property<int>("CL_No")
                        .HasColumnType("int");

                    b.Property<int>("CL_NoParent")
                        .HasColumnType("int");

                    b.Property<short>("CL_Stock")
                        .HasColumnType("smallint");

                    b.HasKey("cbMarq");

                    b.ToTable("F_CATALOGUE");
                });

            modelBuilder.Entity("Web_Api.Model.F_DEPOT", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("DE_Adresse")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("DE_Banque")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DE_Code")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DE_CodePostal")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DE_CodeSociete")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DE_Complement")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("DE_Intitule")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("DE_No")
                        .HasColumnType("int");

                    b.Property<string>("DE_Pays")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<short?>("DE_Principal")
                        .HasColumnType("smallint");

                    b.Property<string>("DE_Ville")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("cbMarq");

                    b.ToTable("F_DEPOT");
                });

            modelBuilder.Entity("Web_Api.Model.F_DOCENTETE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("CT_NumPayeur")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("DE_No")
                        .HasColumnType("int");

                    b.Property<DateTime>("DO_Date")
                        .HasColumnType("datetime2");

                    b.Property<short>("DO_Domaine")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DO_NetAPayer")
                        .HasColumnType("decimal(24,13)");

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("DO_Ref")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DO_Tiers")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal>("DO_TotalHT")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("DO_TotalHTNet")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("DO_TotalTTC")
                        .HasColumnType("decimal(24,13)");

                    b.Property<short>("DO_Type")
                        .HasColumnType("smallint");

                    b.Property<short>("DO_Valide")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.ToTable("F_DOCENTETE");
                });

            modelBuilder.Entity("Web_Api.Model.F_DOCLIGNE", b =>
                {
                    b.Property<int>("cbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cbMarq"));

                    b.Property<string>("AR_Ref")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("CT_Num")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("DL_Design")
                        .HasMaxLength(69)
                        .HasColumnType("nvarchar(69)");

                    b.Property<decimal>("DL_MontantHT")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("DL_MontantTTC")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("DL_PrixUnitaire")
                        .HasColumnType("decimal(24,13)");

                    b.Property<decimal>("DL_Qte")
                        .HasColumnType("decimal(24,13)");

                    b.Property<DateTime>("DO_Date")
                        .HasColumnType("datetime2");

                    b.Property<short>("DO_Domaine")
                        .HasColumnType("smallint");

                    b.Property<string>("DO_Piece")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("DO_Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("cbCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cbModification")
                        .HasColumnType("datetime2");

                    b.HasKey("cbMarq");

                    b.ToTable("F_DOCLIGNE");
                });
#pragma warning restore 612, 618
        }
    }
}
